import styles from '@/styles/Home.module.css';
import { Raleway } from 'next/font/google';
import Head from 'next/head';

const raleway = Raleway({ subsets: ['latin'] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>HI</main>
    </>
  );
};

export default Home;
